import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} flex flex-col bg-gray-50
          text-gray-950 relative dark:bg-gray-900 dark:text-gray-50 dark:text-opacity-90  antialiased`}
      >
        <Navbar />
        <div className="bg-[#fbe2e3] absolute top-[-6rem] flex-1 -z-[10]
        right-[11rem] h-[31.25rem] w-[31.25rem] rounded-full blur-[10rem]
         sm:w-[68.75rem] dark:bg-[#946263]"></div>

         <div className="bg-[#dbd7fb] absolute top-[-1rem] -z-[10] flex-1 left-[-35rem]
         h-[31.25rem] w-[50rem] rounded-full blur-[10rem] sm:w-[68.75rem] md:left-[-33rem] lg:left-[-28rem]
          xl:left-[-15rem] 2xl:left-[-5rem] dark:bg-[#676394]"></div>
        {children}
      </body>
    </html>
  );
}
